<div class="row">
    <div class="col s4 m4">
        <div class="card indigo darken-1">
            <div class="card-content white-text">
                <span class="card-title">Episodes<i class="material-icons right">playlist_play</i></span>
                <p>This list is obtain from a request to the API. But you can add your episodes by yourself</p>
            </div>
            <div class="card-action">
                <a href="index/episode">Thrid API</a>
                <a href="/episodes">Own API</a>
            </div>
        </div>
    </div>
    <div class="col s4 m4">
        <div class="card indigo darken-1">
            <div class="card-content white-text">
                <span class="card-title">Locations<i class="material-icons right">location_searching</i></span>
                <p>This list is obtain from a request to the API. But you can add your locations by yourself</p>
            </div>
            <div class="card-action">
                <a href="index/location">Thrid API</a>
                <a href="/episodes">Own API</a>
            </div>
        </div>
    </div>
    <div class="col s4 m4">
        <div class="card indigo darken-1">
            <div class="card-content white-text">
                <span class="card-title">Characters<i class="material-icons right">people</i></span>
                <p>This list is obtain from a request to the API. Are you tired of the same characters? Build your own now!</p>
            </div>
            <div class="card-action">
                <a href="index/character">Thrid API</a>
                <a href="/characters">Own API</a>
            </div>
        </div>
    </div>
</div>