<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["characters", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Create characters</h1>
</div>

<?php echo $this->getContent(); ?>

<form action="characters/create" class="form-horizontal" method="post">
    <div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldStatus" class="col-sm-2 control-label">Status</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["status", "size" => 30, "class" => "form-control", "id" => "fieldStatus"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldSpecies" class="col-sm-2 control-label">Species</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["species", "size" => 30, "class" => "form-control", "id" => "fieldSpecies"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldType" class="col-sm-2 control-label">Type</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["type", "size" => 30, "class" => "form-control", "id" => "fieldType"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldGender" class="col-sm-2 control-label">Gender</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["gender", "size" => 30, "class" => "form-control", "id" => "fieldGender"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldOrigin" class="col-sm-2 control-label">Origin</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["origin", "size" => 30, "class" => "form-control", "id" => "fieldOrigin"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLocation" class="col-sm-2 control-label">Location</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["location", "size" => 30, "class" => "form-control", "id" => "fieldLocation"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldImageUrl" class="col-sm-2 control-label">Image Of Url</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["image_url", "size" => 30, "class" => "form-control", "id" => "fieldImageUrl"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldUrl" class="col-sm-2 control-label">Url</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["url", "size" => 30, "class" => "form-control", "id" => "fieldUrl"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCreated" class="col-sm-2 control-label">Created</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["created", "size" => 30, "class" => "form-control", "id" => "fieldCreated"]) ?>
    </div>
</div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
        </div>
    </div>
</form>
